language: node_js
sudo: false
git:
  depth: 10

os:
  - windows
  - linux

node_js:
  - "8"
  - "10"
  - "12"

install:
  - npm version
  - npm install
script:
  - npm test

after_success:
- ./node_modules/.bin/codecov

# safelist (prevent double builds in PRs)
branches:
  only:
  - master
  - /^greenkeeper/.*$/
