# This workflow will do an install of the @adobe/aio-cli
# This will surface any plugin/dependency issues when installing

name: Daily - test install aio-cli

on:
  schedule:
    # run daily at midnight
    - cron: '0 0 * * *'

jobs:
  build:
    if: github.repository == 'adobe/aio-cli'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [18, 20, 22, 24]
        os: [ubuntu-latest]

    steps:
    - name: npm
      env:
        NPM_CONFIG_PREFIX: "~/.npm-global"
      run: |
        npm i -g @adobe/aio-cli
    - name: Slack Notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: 'Node version'
        SLACK_MESSAGE: ${{ matrix.node }}
        SLACK_COLOR: ${{ job.status == 'success' && 'good' || job.status == 'cancelled' && '#808080' || 'danger' }}
