# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
  merge_group:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.4.1
      with:
        node-version: ${{ matrix.node-version }}
    - run: rm package-lock.json
    - run: npm i --package-lock --package-lock-only --legacy-peer-deps
    - run: npm ci --legacy-peer-deps
    - run: npm run build --if-present
    - run: npm test
    - name: run tests
      run: |
        ./bin/run --help
        ./bin/run plugins --core
        ./bin/run config --help
        ./bin/run console --help
        ./bin/run runtime --help
    - name: upload coverage
      if: success()
      uses: codecov/codecov-action@v4
      with:
        name: ${{ runner.os }} node.js ${{ matrix.node-version }}
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false